"""Ports: repository protocols the application depends on.

Interfaces only; concrete implementations live in the infra layer.
"""

from __future__ import annotations

import uuid
from typing import Protocol

from dispatcher.models import Assignment, Service, Task


class TaskRepository(Protocol):
    def add(self, task: Task) -> None: ...
    def get(self, task_id: uuid.UUID) -> Task | None: ...
    def update(self, task: Task) -> None: ...
    def list_pending(self) -> list[Task]: ...


class ServiceRepository(Protocol):
    def add(self, service: Service) -> None: ...
    def get(self, service_id: uuid.UUID) -> Service | None: ...
    def update(self, service: Service) -> None: ...
    def list_all(self) -> list[Service]: ...


class AssignmentRepository(Protocol):
    def add(self, assignment: Assignment) -> None: ...
    def get(self, assignment_id: uuid.UUID) -> Assignment | None: ...
    def update(self, assignment: Assignment) -> None: ...
    def list_active(self) -> list[Assignment]: ...
