"""Ports: protocols the application depends on.

Interfaces only; concrete implementations live in the infra layer.
"""

from __future__ import annotations

import uuid
from typing import Protocol

from docket.domain.models import Assignment, Service, Task


class TaskRepository(Protocol):
    async def add(self, task: Task) -> None: ...
    async def get(self, task_id: uuid.UUID) -> Task | None: ...
    async def update(self, task: Task) -> None: ...
    async def list_pending(self) -> list[Task]: ...


class ServiceRepository(Protocol):
    async def add(self, service: Service) -> None: ...
    async def get(self, service_id: uuid.UUID) -> Service | None: ...
    async def update(self, service: Service) -> None: ...
    async def list_all(self) -> list[Service]: ...


class AssignmentRepository(Protocol):
    async def add(self, assignment: Assignment) -> None: ...
    async def get(self, assignment_id: uuid.UUID) -> Assignment | None: ...
    async def update(self, assignment: Assignment) -> None: ...
    async def list_active(self) -> list[Assignment]: ...


class Broker(Protocol):
    """A pull-based task queue: producers enqueue, consumers pull."""

    def enqueue(self, task: Task) -> None: ...
    def pull(self) -> Task | None: ...
