"""Ports: protocols the application depends on.

Interfaces only; concrete implementations live in the infra layer.
"""

from __future__ import annotations

import uuid
from typing import Protocol

from docket.domain.models import Assignment, Service, Task


class TaskRepository(Protocol):
    async def add(self, task: Task) -> None: ...
    async def get(self, task_id: uuid.UUID) -> Task | None: ...
    async def update(self, task: Task) -> None: ...
    async def list_pending(self) -> list[Task]: ...


class ServiceRepository(Protocol):
    async def add(self, service: Service) -> None: ...
    async def get(self, service_id: uuid.UUID) -> Service | None: ...
    async def update(self, service: Service) -> None: ...
    async def list_all(self) -> list[Service]: ...


class AssignmentRepository(Protocol):
    async def add(self, assignment: Assignment) -> None: ...
    async def get(self, assignment_id: uuid.UUID) -> Assignment | None: ...
    async def update(self, assignment: Assignment) -> None: ...
    async def list_active(self) -> list[Assignment]: ...


class Broker(Protocol):
    """A pull-based task queue with per-consumer leases.

    A consumer identifies itself on ``pull``; the task is leased to it until
    it ``ack``s (done) or ``nack``s (returned to the queue). ack/nack take
    the holder's id so only the lease owner can resolve it. If a consumer
    crashes, ``requeue_service`` returns all of its in-flight tasks.
    """

    async def enqueue(self, task: Task) -> None: ...
    async def pull(self, service_id: uuid.UUID) -> Task | None: ...
    async def ack(self, service_id: uuid.UUID, task_id: uuid.UUID) -> None: ...
    async def nack(
        self, service_id: uuid.UUID, task_id: uuid.UUID
    ) -> None: ...
    async def requeue_service(self, service_id: uuid.UUID) -> None: ...
